### ISSUE TITLE
Implement hot-reloading of entire addon

### ISSUE THREAD

**Issue by moppius** [EmbarkStudios/blender-tools#1]
**Is your feature request related to a problem? Please describe.**
When working on addon development, it would be useful to cleanly reload the entire Embark Addon module and add-on without restarting Blender.
This would also be useful if it can be used for reloading the add-on after an update.

**Describe the solution you'd like**
Using `importlib` seems like a common approach to reload the module and its submodules. The reload order is important, though, since imports may try to bring in objects from submodules that haven't been reloaded yet.

**Describe alternatives you've considered**
The obvious alternative is just telling people to always restart Blender, but this isn't great for iteration when developing, or the user experience when updating.
However, if we want to hot-reload, it _must_ be reliable!
We are currently in a somewhat unstable middle-ground, where the addon may fail to reload after certain types of updates, and then the user needs to restart Blender anyway.

**Additional context**
There is a commented-out section in the `reload_addon()` method defined i then `utils` submodule - during testing this was causing Blender crashes. It may need to move somewhere else (e.g. main module initialization).
There is also the `bpy.ops.script.reload()` operator from Blender, but this does not fully reload the entire add-on module, only the top-level **__init__.py**.

**Comment by GarmOfGnipahellir** [comment]
VSCode users can use https://github.com/JacquesLucke/blender_vscode, it has served me well when working on Blender addons. 
You can reload the addon and see the Blender console output directly in VSCode!

**Comment by moppius** [comment]
Good call, I think @adrianbjorkerud has been using this here at Embark recently with great success!

Maybe we can close this one, since we develop the addon in VSCode anyway.
