### ISSUE TITLE
Exporting creates no files on macOS or Linux

### ISSUE THREAD

**Issue by drewcassidy** [EmbarkStudios/blender-tools#4]
**Describe the bug**
Attempting to export collections does not create files in the correct place, without any error. If there are files produced, I do not know where.

**To Reproduce**
1. Install plugin
2. Set project directory to a directory above the current file
3. make an export collection and try to export it

**Expected behavior**
an fix file is produced at the chosen path

**Screenshots**
<img width="439" alt="Screen Shot 2020-05-19 at 10 24 03 PM" src="https://user-images.githubusercontent.com/3837797/82408003-74a73400-9a1f-11ea-8062-e339eaba2a55.png">
<img width="210" alt="Screen Shot 2020-05-19 at 10 23 44 PM" src="https://user-images.githubusercontent.com/3837797/82408014-78d35180-9a1f-11ea-831e-25b2a6ad2f90.png">

**Device:**
 - OS: macOS Catalina
 - Blender 2.82

**Additional context**
Is this due to the backslash at the beginning of the file path? I don't know why thats there but it must be escaping something, and I cant delete it, the plugin puts it back

**Comment by drewcassidy** [comment]
Yup, its the backslash. see #5 for a fix

**Comment by moppius** [comment]
Let me know if the latest version with your fix merged is working as expected on MacOS now, and I'll close this issue.

**Comment by drewcassidy** [comment]
everything is working!
